/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author aless
 */
public class dlgLogin extends javax.swing.JDialog {
    Main home;
    /**
     * Creates new form frmLogin
     */
    public dlgLogin(Main parent) {
        super();
        initComponents();
        home = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAccedi = new javax.swing.JPanel();
        pnlCredenziali = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        btnAccedi = new javax.swing.JButton();
        cbxRicordami = new javax.swing.JCheckBox();
        pnlRegistrati = new javax.swing.JPanel();
        pnlCredenziali2 = new javax.swing.JPanel();
        lblUsername1 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        lblPassword1 = new javax.swing.JLabel();
        pswPassword1 = new javax.swing.JPasswordField();
        lblTavoli = new javax.swing.JLabel();
        spnTavoli = new javax.swing.JSpinner();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnRegistrati = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        pnlCredenziali.setLayout(new java.awt.GridLayout(2, 2, 0, 10));

        lblUsername.setText("Username");
        pnlCredenziali.add(lblUsername);
        pnlCredenziali.add(txtUsername);

        lblPassword.setText("Password");
        pnlCredenziali.add(lblPassword);
        pnlCredenziali.add(pswPassword);

        btnAccedi.setText("Accedi");
        btnAccedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccediActionPerformed(evt);
            }
        });

        cbxRicordami.setText("Ricordami");

        javax.swing.GroupLayout pnlAccediLayout = new javax.swing.GroupLayout(pnlAccedi);
        pnlAccedi.setLayout(pnlAccediLayout);
        pnlAccediLayout.setHorizontalGroup(
            pnlAccediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccediLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(pnlCredenziali, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccediLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlAccediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccedi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRicordami))
                .addGap(117, 117, 117))
        );
        pnlAccediLayout.setVerticalGroup(
            pnlAccediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccediLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlCredenziali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxRicordami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccedi)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Accedi", pnlAccedi);

        pnlCredenziali2.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        lblUsername1.setText("Username");
        pnlCredenziali2.add(lblUsername1);
        pnlCredenziali2.add(txtUsername1);

        lblPassword1.setText("Password");
        pnlCredenziali2.add(lblPassword1);
        pnlCredenziali2.add(pswPassword1);

        lblTavoli.setText("Numero tavoli");
        pnlCredenziali2.add(lblTavoli);

        spnTavoli.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        pnlCredenziali2.add(spnTavoli);

        lblNome.setText("Nome ristorante");
        pnlCredenziali2.add(lblNome);
        pnlCredenziali2.add(txtNome);

        btnRegistrati.setText("Registrati");
        btnRegistrati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistratiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistratiLayout = new javax.swing.GroupLayout(pnlRegistrati);
        pnlRegistrati.setLayout(pnlRegistratiLayout);
        pnlRegistratiLayout.setHorizontalGroup(
            pnlRegistratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistratiLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(pnlCredenziali2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistratiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrati)
                .addGap(113, 113, 113))
        );
        pnlRegistratiLayout.setVerticalGroup(
            pnlRegistratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistratiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlCredenziali2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrati)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrati", pnlRegistrati);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistratiActionPerformed
        this.dispose();
        home.setLogged(true);
    }//GEN-LAST:event_btnRegistratiActionPerformed

    private void btnAccediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccediActionPerformed
        Database.login(txtUsername.getText(), String.valueOf(pswPassword.getPassword()));
        
        
        if(cbxRicordami.isSelected())
        {
            try
            {
                Account.salvaAccount();
            }
            catch (IOException ex)
            {
                Logger.getLogger(dlgLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if(Account.isLogged())
            this.dispose();        
    }//GEN-LAST:event_btnAccediActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccedi;
    private javax.swing.JButton btnRegistrati;
    private javax.swing.JCheckBox cbxRicordami;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblTavoli;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPanel pnlAccedi;
    private javax.swing.JPanel pnlCredenziali;
    private javax.swing.JPanel pnlCredenziali2;
    private javax.swing.JPanel pnlRegistrati;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JPasswordField pswPassword1;
    private javax.swing.JSpinner spnTavoli;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
