
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author aless
 */
public class dlgModifica extends javax.swing.JDialog {
    
    /**
     * Creates new form dlgRimuovi
     */
    public void aggiornaMenu()
    {
        ArrayList<Piatto> menu = Database.getMenu();
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Menù");
        
        DefaultMutableTreeNode antipasti = new DefaultMutableTreeNode("Antipasti");
        DefaultMutableTreeNode primi = new DefaultMutableTreeNode("Primi");
        DefaultMutableTreeNode secondi = new DefaultMutableTreeNode("Secondi");
        DefaultMutableTreeNode pizze = new DefaultMutableTreeNode("Pizze");
        DefaultMutableTreeNode dessert = new DefaultMutableTreeNode("Dessert");
        DefaultMutableTreeNode bevande = new DefaultMutableTreeNode("Bevande");
        
        
       
        
        DefaultTreeModel model = new DefaultTreeModel(root);
        treMenù.setModel(model);
        
        for(Piatto p : menu)
        {
            if(p.getCategoria().equals("Antipasti"))
                antipasti.add(new DefaultMutableTreeNode(p.getNome()));
            else if(p.getCategoria().equals("Primi"))
                primi.add(new DefaultMutableTreeNode(p.getNome()));
            else if(p.getCategoria().equals("Secondi"))
                secondi.add(new DefaultMutableTreeNode(p.getNome()));
            else if(p.getCategoria().equals("Pizze"))
                pizze.add(new DefaultMutableTreeNode(p.getNome()));
            else if(p.getCategoria().equals("Dessert"))
                dessert.add(new DefaultMutableTreeNode(p.getNome()));
            else if(p.getCategoria().equals("Bevande"))
                bevande.add(new DefaultMutableTreeNode(p.getNome()));
        }
        
        if(!antipasti.isLeaf())
            root.add(antipasti);
        if(!primi.isLeaf())
            root.add(primi);
        if(!secondi.isLeaf())
            root.add(secondi);
        if(!pizze.isLeaf())
            root.add(pizze);
        if(!dessert.isLeaf())
            root.add(dessert);
        if(!bevande.isLeaf())
            root.add(bevande);
        
        for (int i = 0; i < treMenù.getRowCount(); i++)
        {
            treMenù.expandRow(i);
        }
    }
    
    public dlgModifica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        aggiornaMenu();
    }
    
    private void piattoSelezionato(String piatto)
    {
        Piatto p = Database.getPiatto(piatto);
        
        dlgModificaMenu modificaPiatto = new dlgModificaMenu(this, true, p);
        modificaPiatto.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrMenù = new javax.swing.JScrollPane();
        treMenù = new javax.swing.JTree();
        btnAggiungi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menù");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treMenù.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        scrMenù.setViewportView(treMenù);
        treMenù.addMouseListener(
            new MouseAdapter() {
                public void mousePressed(MouseEvent e) {
                    DefaultMutableTreeNode node = (DefaultMutableTreeNode) treMenù.getLastSelectedPathComponent();
                    if(treMenù.getRowForLocation(e.getX(), e.getY()) != -1)
                    if(e.getClickCount() == 2 && node.isLeaf())
                    piattoSelezionato(node.toString());
                }
            }
        );

        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMenù, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAggiungi)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAggiungi)
                    .addComponent(scrMenù, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        dlgAggiungi aggiungi = new dlgAggiungi(this, true);
        aggiungi.setVisible(true);
    }//GEN-LAST:event_btnAggiungiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JScrollPane scrMenù;
    private javax.swing.JTree treMenù;
    // End of variables declaration//GEN-END:variables
}
