/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author aless
 */
public class dlgRistorante extends javax.swing.JDialog {
    frmHome p;
    /**
     * Creates new form dlgRistorante
     */
    public dlgRistorante(frmHome parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        username.setText(Account.getUSERNAME());
        spnTavoli.setValue(Account.getTAVOLI());
        txtRistorante.setText(Account.getRISTORANTE());
        
        p = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        pnlDati = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        lblTavoli = new javax.swing.JLabel();
        spnTavoli = new javax.swing.JSpinner();
        lblRistorante = new javax.swing.JLabel();
        txtRistorante = new javax.swing.JTextField();
        pnlBottoni = new javax.swing.JPanel();
        btnSalva = new javax.swing.JButton();
        btnChiudi = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDati.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        lblUsername.setText("Username");
        pnlDati.add(lblUsername);
        pnlDati.add(username);

        lblTavoli.setText("Numero tavoli");
        pnlDati.add(lblTavoli);

        spnTavoli.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        pnlDati.add(spnTavoli);

        lblRistorante.setText("Nome ristorante");
        pnlDati.add(lblRistorante);
        pnlDati.add(txtRistorante);

        pnlBottoni.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        btnSalva.setText("Salva");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnSalva);

        btnChiudi.setText("Chiudi");
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnChiudi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBottoni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(pnlBottoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        if((Integer) spnTavoli.getValue() != Account.getTAVOLI())
            Account.setTAVOLI((Integer) spnTavoli.getValue());
        if(!txtRistorante.getText().equals(Account.getRISTORANTE()))
            Account.setRISTORANTE(txtRistorante.getText());
        
        Database.update();
        p.refresh();
    }//GEN-LAST:event_btnSalvaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnSalva;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblRistorante;
    private javax.swing.JLabel lblTavoli;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottoni;
    private javax.swing.JPanel pnlDati;
    private javax.swing.JSpinner spnTavoli;
    private javax.swing.JTextField txtRistorante;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
