/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author aless
 */
public class dlgRistorante extends javax.swing.JDialog {

    /**
     * Creates new form dlgRistorante
     */
    public dlgRistorante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDati = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblTavoli = new javax.swing.JLabel();
        spnTavoli = new javax.swing.JSpinner();
        pnlBottoni = new javax.swing.JPanel();
        btnSalva = new javax.swing.JButton();
        btnChiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDati.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        lblUsername.setText("Username");
        pnlDati.add(lblUsername);
        pnlDati.add(txtUsername);

        lblTavoli.setText("Numero tavoli");
        pnlDati.add(lblTavoli);

        spnTavoli.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        pnlDati.add(spnTavoli);

        pnlBottoni.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        btnSalva.setText("Salva");
        pnlBottoni.add(btnSalva);

        btnChiudi.setText("Chiudi");
        pnlBottoni.add(btnChiudi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBottoni, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(pnlBottoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel lblTavoli;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottoni;
    private javax.swing.JPanel pnlDati;
    private javax.swing.JSpinner spnTavoli;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
