import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aless
 */
public class frmHome extends javax.swing.JFrame {
    
    private boolean logged;
    /**
     * Creates new form Home
     */
    public frmHome() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        dlgLogin login = new dlgLogin(this, true);
        login.setVisible(true);
        
        login.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if(!logged)
                    System.exit(0);
            }
        });
    }
    
    public void setLogged(boolean logged)
    {
        this.logged = logged;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        itmChiudi = new javax.swing.JMenuItem();
        mnuMenù = new javax.swing.JMenu();
        itmAggiungi = new javax.swing.JMenuItem();
        itmModifica = new javax.swing.JMenuItem();
        itmRimuovi = new javax.swing.JMenuItem();
        mnuAiuto = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy order");

        mnuFile.setText("File");

        itmChiudi.setMnemonic('c');
        itmChiudi.setText("Chiudi");
        itmChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmChiudiActionPerformed(evt);
            }
        });
        mnuFile.add(itmChiudi);

        jMenuBar1.add(mnuFile);

        mnuMenù.setText("Menù");

        itmAggiungi.setText("Aggiungi");
        itmAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAggiungiActionPerformed(evt);
            }
        });
        mnuMenù.add(itmAggiungi);

        itmModifica.setText("Modifica");
        mnuMenù.add(itmModifica);

        itmRimuovi.setText("Rimuovi");
        itmRimuovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRimuoviActionPerformed(evt);
            }
        });
        mnuMenù.add(itmRimuovi);

        jMenuBar1.add(mnuMenù);

        mnuAiuto.setText("Aiuto");

        itmAbout.setText("Su di noi");
        itmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAboutActionPerformed(evt);
            }
        });
        mnuAiuto.add(itmAbout);

        jMenuBar1.add(mnuAiuto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmChiudiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmChiudiActionPerformed

    private void itmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAboutActionPerformed
        dlgAbout about = new dlgAbout(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_itmAboutActionPerformed

    private void itmAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAggiungiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAggiungiActionPerformed

    private void itmRimuoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRimuoviActionPerformed
        dlgRimuovi rimuovi = new dlgRimuovi(this, true);
        rimuovi.setVisible(true);
        
    }//GEN-LAST:event_itmRimuoviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmAggiungi;
    private javax.swing.JMenuItem itmChiudi;
    private javax.swing.JMenuItem itmModifica;
    private javax.swing.JMenuItem itmRimuovi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAiuto;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuMenù;
    // End of variables declaration//GEN-END:variables
}
